---
title: "Batch_correction"
output: html_document
date: "2023-11-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Documents/GitHub/Test_DEG_methods-single_cell/batch_correction")

```

```{r}
library(sva)
library(plyr)
library(DESeq2)
library(tidyverse)
library(pheatmap)
library(RColorBrewer)
```




## Gettin the microarray data

Expression.csv is a file where each column is a sample, each row a gene and in each cell I have the expression level. In this specific case is microarray data.

Samples_age_class.csv contains the metadata of each sample, being the most important the Geo_accesion, Experiment and X

```{r}
expression_path =  "Expression.csv"
samples_data_path = "Samples_age_class.csv"



```




```{r}
counts<- read.csv(expression_path)
exp_design <- read.csv(samples_data_path)

```

```{r message=FALSE, warning=FALSE}
counts <- read.csv("Pseudobulk_clean_mm.csv", row.names = "Symbol")
exp_design <- read.csv("Experiment_design_mm.csv", row.names = "Sample")
```

```{r message=FALSE, warning=FALSE}
cts <- as.matrix(counts)

exp_design$Condition <- factor(exp_design$Condition)
exp_design$Batch <- factor(exp_design$Batch)

batches_unique = unique(sort(exp_design$Batch))
batches = exp_design$Batch
batch_seq = seq(0, length(batches_unique))
batches <- mapvalues(batches, from = batches_unique, to = batch_seq)

exp_design$batch_num <- batches
todrop = rownames(exp_design[exp_design$batch_num == 3,])
exp_design <- exp_design[!(row.names(exp_design) %in% todrop),]
cts <- cts[,colnames(cts)!= todrop]
batches = exp_design$batch_num
batches <- as.numeric(batches)
```




```{r}
# Perform batch correction using ComBat
# Assuming the 'GB_ACC' column is numeric and all other columns are numeric
# You may need to modify the model matrix accordingly based on your data

model_matrix <- model.matrix(~1, data = filtered_dfs[[1]])

combat_result <- sva::ComBat(dat = do.call(rbind, filtered_dfs),
                        batch = factor(rep(1:length(filtered_dfs), sapply(filtered_dfs, nrow))),
                        mod = model_matrix)

# Create a data frame with the corrected values
corrected_df <- data.frame(combat_result)

# Save the corrected data to a new CSV file
write.csv(corrected_df, file = "corrected_data.csv", row.names = FALSE)

# Print a message indicating the process is complete
cat("Batch correction and merging completed. Corrected data saved to 'corrected_data.csv'.\n")
```


```{r}

# Assuming filtered_df is your list of data frames

# 1. Create dataframe "master_df"
genes <- lapply(filtered_df, function(df) unique(row.names(df)))

# 2. Assign genes to only the unique values of genes
unique_genes <- unique(unlist(genes))

# 3. Create master_df as an empty dataframe with the row names as genes
master_df <- data.frame(stringsAsFactors = FALSE, row.names = unique_genes)


# 2. Create an empty list "batches_n"
batches_n <- list()

# 3. For each df in filtered_df
for (df in filtered_df) {
  
  # 3.1 Count how many columns it has and add it to batches_n
  batches_n <- c(batches_n, ncol(df))
  missing_rows <- setdiff(row.names(master_df), row.names(df))

  # Create a dataframe with NAs for the missing rows
  missing_df <- data.frame(GB_ACC = missing_rows, stringsAsFactors = FALSE, row.names = missing_rows)
  missing_df[, names(df)] <- NA
  missing_df <- missing_df[, names(df), drop = FALSE]

  # Bind the missing_df to df
  df_filled <- rbind(df, missing_df)
  # 3.2 Append the df to master_df
  master_df <- cbind(master_df, df_filled)
  #master_df <- merge(master_df, df, by.x = 0, by.y = 0, all = TRUE)

}

# Convert the list of column counts to a data frame
batches_n_df <- data.frame(Batch_Column_Count = unlist(batches_n))

```






```{r}
distinct_counts <- sapply(master_df, function(x) n_distinct(x))


```


```{r}
result_list <- c()
ind= 0
for (i in batches_n_df[[1]]) {
  result_list <- c(result_list, rep(ind, i))
  ind=ind+1
}
result_list
```


```{r}

model_matrix <- model.matrix(~1, data = master_df)
batches <- factor(result_list)
model_matrix <- model.matrix(~ 0 + batches)

  # Apply ComBat
combat_result <- sva::ComBat(dat = master_df,
                          batch = batches,  # Assuming one batch per data frame
                          mod = model_matrix)
```
```{r}
master_df
write.csv(master_df, "master_df")
```





