---
title: "edgeR_combat"
author: "Jacopo Umberto Verga"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# edgeR combat

Test perforamces edgeR with the pseudobulk counts obtained previously corrected by the batch effect using combat.


```{r message=FALSE, warning=FALSE}
library(edgeR)
library(sva)
library(plyr)
library(tidyverse)
library(pheatmap)
library(RColorBrewer)
library(preprocessCore)
```

Load counts and experiment design

```{r message=FALSE, warning=FALSE}
counts <- read.csv("Pseudobulk_clean_healthy.csv", row.names = "Symbol")
exp_design <- read.csv("Experiment_design_healthy.csv", row.names = "Sample")
```

```{r message=FALSE, warning=FALSE}
cts <- as.matrix(counts)

#exp_design$Condition <- factor(exp_design$Condition)
#exp_design$Batch <- factor(exp_design$Batch)

batches_unique = unique(sort(exp_design$Batch))
batches = exp_design$Batch
batches <- mapvalues(batches, from = batches_unique, to = c (1, 2, 3))#, 4, 5, 6))

exp_design$batch_num <- batches
#todrop = rownames(exp_design[exp_design$batch_num == 3,])
#exp_design <- exp_design[!(row.names(exp_design) %in% todrop),]
#cts <- cts[,colnames(cts)!= todrop]
batches = exp_design$batch_num
batches <- as.numeric(batches)


```

```{r}
cts_num <- matrix(as.numeric(cts),    # Convert to numeric matrix
                  ncol = ncol(cts))
rownames(cts_num) <- rownames(cts)
colnames(cts_num) <- colnames(cts)
dim(cts_num)
```

```{r}
adjusted <- ComBat_seq(cts_num, batch=batches, group=NULL)

```



```{r}
dglist <- DGEList(adjusted, genes=rownames(adjusted))
dglist <- calcNormFactors(dglist, method="TMM")
sampleType<- exp_design$Condition
sampleReplicate <-batches
designMat <- model.matrix(~sampleReplicate + sampleType)
```


```{r}
dglist <- estimateGLMCommonDisp(dglist, design=designMat)
dglist <- estimateGLMTrendedDisp(dglist, design=designMat)
dglist <- estimateGLMTagwiseDisp(dglist, design=designMat)
```


```{r}
fit <- glmFit(dglist, designMat)
lrt <- glmLRT(fit, coef=ncol(fit$design))

edgeR_result <- topTags(lrt, n = nrow(adjusted))$table %>%
  mutate(absLFC = abs(logFC), logFC = logFC*-1) %>%
  filter(FDR < 0.05) %>%
  filter(absLFC >= 0.03)

write.csv(edgeR_result, "edgeR_combat_healthy.csv")
```
