---
title: "limma-voom_combat"
author: "Jacopo Umberto Verga"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# limma-voom

Test perforamces limma-voom with the pseudobulk counts obtained previously corrected by the batch effect using combat.


```{r message=FALSE, warning=FALSE}
library(sva)
library(plyr)
library(edgeR)
library(tidyverse)
library(pheatmap)
library(RColorBrewer)
```

Load counts and experiment design

```{r message=FALSE, warning=FALSE}
counts <- read.csv("Pseudobulk_clean_mm.csv", row.names = "Symbol")
exp_design <- read.csv("Experiment_design_mm.csv", row.names = "Sample")
exp_design$Condition <- sub(" ", "_", exp_design$Condition)
```

```{r message=FALSE, warning=FALSE}
cts <- as.matrix(counts)

exp_design$Condition <- factor(exp_design$Condition)
exp_design$Batch <- factor(exp_design$Batch)

batches_unique = unique(sort(exp_design$Batch))
batches = exp_design$Batch
batches <- mapvalues(batches, from = batches_unique, to = c (1, 2, 3, 4, 5, 6))

exp_design$batch_num <- batches
#todrop = rownames(exp_design[exp_design$batch_num == 3,])
#exp_design <- exp_design[!(row.names(exp_design) %in% todrop),]
#cts <- cts[,colnames(cts)!= todrop]
batches = exp_design$batch_num
batches <- as.numeric(batches)
cl_unique = unique(sort(exp_design$Condition))
cl = exp_design$Condition
cl = mapvalues(cl, from = cl_unique, to = c(0,1))
```

```{r}
adjusted <- ComBat_seq(cts, batch=batches, group=NULL)
```


```{r}
all(rownames(exp_design) %in% colnames(cts))
all(rownames(exp_design) == colnames(cts))
```



```{r}
d0 <- DGEList(cts)
d0 <- calcNormFactors(d0)
```

```{r}
snames <- colnames(cts) # Sample names
conditions <- interaction(cl)
```

```{r}
mm <- model.matrix(~ 0 + conditions + batches)
y <- voom(d0, mm, plot = T)
```
```{r}
fit <- lmFit(y, mm)
head(coef(fit))
```

```{r}
contr <- makeContrasts(conditions0 - conditions1, levels = colnames(coef(fit)))
contr
```


```{r}
tmp <- contrasts.fit(fit, contr)
tmp <- eBayes(tmp)
```


```{r}
top.table <- topTable(tmp, sort.by = "P", n = Inf)%>%
  mutate(absFLC = abs(logFC)) %>%
  filter(absFLC >= 0.3) %>%
  filter(adj.P.Val < 0.05)

write.csv(top.table, "limma_combat_mm.csv")
```

