---
title: "wilcoxon"
author: "Jacopo Umberto Verga"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# wilcoxon

Test perforamces wilcoxon with the pseudobulk counts obtained previously corrected by the batch effect using combat.


```{r message=FALSE, warning=FALSE}
library(sva)
library(plyr)
library(RankProd)
library(tidyverse)
library(pheatmap)
library(RColorBrewer)
library(preprocessCore)
```

Load counts and experiment design

```{r message=FALSE, warning=FALSE}
counts <- read.csv("Pseudobulk_clean_healthy.csv", row.names = "Symbol")
exp_design <- read.csv("Experiment_design_healthy.csv", row.names = "Sample")
```

```{r message=FALSE, warning=FALSE}
cts <- as.matrix(counts)

#exp_design$Condition <- factor(exp_design$Condition)
#exp_design$Batch <- factor(exp_design$Batch)

batches_unique = unique(sort(exp_design$Batch))
batches = exp_design$Batch
batches <- mapvalues(batches, from = batches_unique, to = c (1, 2, 3))#, 4, 5, 6))

exp_design$batch_num <- batches
#todrop = rownames(exp_design[exp_design$batch_num == 3,])
#exp_design <- exp_design[!(row.names(exp_design) %in% todrop),]
#cts <- cts[,colnames(cts)!= todrop]
batches = exp_design$batch_num
batches <- as.numeric(batches)

cl_unique = unique(sort(exp_design$Condition))
cl = exp_design$Condition
cl = mapvalues(cl, from = cl_unique, to = c(0,1))

```




```{r}
cts_num <- matrix(as.numeric(cts),    # Convert to numeric matrix
                  ncol = ncol(cts))
rownames(cts_num) <- rownames(cts)
colnames(cts_num) <- colnames(cts)
dim(cts_num)
```
```{r}
adjusted <- ComBat_seq(cts_num, batch=batches, group=NULL)
```


```{r}
adjusted_norm = adjusted
for (i in 1:dim(adjusted)[2]){
  norm_column = (adjusted[,i]/sum(adjusted[,i])*10000)
  adjusted_norm[,i] = log2((norm_column+1))
}

#norm= normalize.quantiles.robust(adjusted, copy = TRUE)
#norm = log2(adjusted+1)
#rownames(norm)=rownames(adjusted)
#colnames(norm)=colnames(adjusted)
```

```{r}
conditions <- factor(t(exp_design$Condition))
pvalues <- sapply(1:nrow(adjusted_norm), function(i){
  data <- cbind.data.frame(gene =as.numeric((adjusted_norm[i,])), conditions)
  p <- wilcox.test(gene~conditions, data)$p.value
  return(p)
  })
fdr <- p.adjust(pvalues, method = "fdr")
conditionsLevel <- levels(conditions)
dataCon1 <- adjusted_norm[,c(which(conditions==conditionsLevel[2]))]
dataCon2 <- adjusted_norm[,c(which(conditions==conditionsLevel[1]))]
foldChanges <- log2(rowMeans(dataCon1)/rowMeans(dataCon2))

outRst <- data.frame(log2foldChange = foldChanges, pValues = pvalues, FDR = fdr)
rownames(outRst) <- rownames(adjusted_norm)
outRst <- na.omit(outRst)
outRst$absLFC <- abs(outRst$log2foldChange)
outRst <- outRst[outRst$FDR < 0.05,]
outRst <- outRst[outRst$absLFC >= 0.3,]

write.csv(outRst, file = "wilcoxon_healthy.csv")
```